[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-name.onrender.com"

[context.deploy-preview.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-name.onrender.com"

[context.branch-deploy.environment]
  NEXT_PUBLIC_API_URL = "https://your-backend-name.onrender.com"
